# Generated by Django 5.2.6 on 2026-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rp_registration", "0003_remove_registeredentity_trust_service_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityentitlement",
            name="entitlement_uri",
            field=models.URLField(
                help_text="EUDI Wallet Entitlement URIs: http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/PID_Issuer, http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/QEAA_Provider, http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/WalletProvider, http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/RelyingParty",
                max_length=2048,
            ),
        ),
    ]
