# Generated by Django 5.2.6 on 2026-05-28 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredentity",
            name="registered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
