# Generated by Django 5.2.6 on 2026-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityentitlement",
            name="entitlement_type",
            field=models.CharField(
                choices=[
                    ("Service_Provider", "Service Provider"),
                    ("PID_Provider", "PID Provider"),
                    ("QEAA_Provider", "Qualified EAA Provider"),
                    ("Non_Q_EAA_Provider", "Non-Qualified EAA Provider"),
                    ("PUB_EAA_Provider", "Public EAA Provider"),
                    (
                        "QCert_for_ESig_Provider",
                        "Qualified Certificate for E-Signature Provider",
                    ),
                    (
                        "QCert_for_ESeal_Provider",
                        "Qualified Certificate for E-Seal Provider",
                    ),
                    (
                        "rQSigCDs_Provider",
                        "Remote Qualified Signature Creation Device Provider",
                    ),
                    (
                        "rQSealCDs_Provider",
                        "Remote Qualified Seal Creation Device Provider",
                    ),
                    (
                        "ESig_ESeal_Creation_Provider",
                        "E-Signature/E-Seal Creation Provider",
                    ),
                    ("Intermediary", "Intermediary"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="entityentitlement",
            name="entitlement_uri",
            field=models.URLField(
                help_text="ETSI Entitlement URIs per TS5: https://uri.etsi.org/19475/Entitlement/Service_Provider, https://uri.etsi.org/19475/Entitlement/PID_Provider, https://uri.etsi.org/19475/Entitlement/QEAA_Provider, https://uri.etsi.org/19475/Entitlement/PUB_EAA_Provider, https://uri.etsi.org/19475/Entitlement/Non_Q_EAA_Provider, https://uri.etsi.org/19475/Entitlement/QCert_for_ESig_Provider, https://uri.etsi.org/19475/Entitlement/QCert_for_ESeal_Provider, https://uri.etsi.org/19475/Entitlement/rQSigCDs_Provider, https://uri.etsi.org/19475/Entitlement/rQSealCDs_Provider, https://uri.etsi.org/19475/Entitlement/ESig_ESeal_Creation_Provider",
                max_length=2048,
            ),
        ),
    ]
