# Generated by Django 5.2.6 on 2026-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_registered_at_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredentity",
            name="domain_uri",
            field=models.URLField(
                blank=True,
                help_text="URL of the entity's own domain/service (used for certificate SANs)",
                max_length=2048,
                null=True,
            ),
        ),
    ]
