# Generated by Django 5.2.6 on 2026-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_add_domain_uri_to_registered_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredentity",
            name="instance_uri",
            field=models.URLField(
                blank=True,
                help_text="Full service endpoint of this instance, incl. port (SAN uniformResourceIdentifier for certificates)",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registeredentity",
            name="domain_uri",
            field=models.URLField(
                blank=True,
                help_text="Domain/host of the entity's service (SAN dNSName for certificates)",
                max_length=2048,
                null=True,
            ),
        ),
    ]
