# Generated by Django 5.2.6 on 2026-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_policy_type_uri_data_migration"),
        ("legal_entities", "0001_initial"),
        ("registry", "0004_change_legal_entity_to_foreignkey"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registeredentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registry_uri", ""), _negated=True),
                fields=("legal_entity", "registry_uri"),
                name="unique_legal_entity_registry_uri",
            ),
        ),
    ]
