# Generated by Django 5.2.6 on 2026-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_policy_type_uri_data_migration"),
        ("legal_entities", "0001_initial"),
        ("registry", "0005_unique_legal_entity_registry_uri"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registeredentity",
            name="unique_legal_entity_registry_uri",
        ),
        migrations.AddConstraint(
            model_name="registeredentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registry_uri", ""), _negated=True),
                fields=("registry_uri",),
                name="unique_registered_entity_registry_uri",
            ),
        ),
    ]
