version: "3.2"

services:
  django:
    build: .
    image: django-taxonomy
    container_name: django-taxonomy
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - "taxonomy_static_files:/var/www/static/"
      - "taxonomy_media_files:/var/www/media/"
      - "./taxonomy:/app"
    # Use runserver for local development not uwsgi
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"

  postgres:
    image: postgres:14
    container_name: postgres-taxonomy
    environment:
      POSTGRES_DB: taxonomy
      POSTGRES_PASSWORD: supersecret
    volumes:
      - "taxonomy_dbdata:/var/lib/postgresql/data"
    # Expose port to localhost for debugging
    ports:
      - "127.0.0.1:5433:5432"

  redis:
    image: redis:6.2
    container_name: redis-taxonomy

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-taxonomy
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=b0lag


volumes:
  taxonomy_dbdata:
  taxonomy_static_files:
  taxonomy_media_files:
