version: "3.2"

services:
  django:
    build: .
    image: django-ms-registry
    container_name: django-ms-registry
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - "ms_registry_static_files:/var/www/static/"
      - "ms_registry_media_files:/var/www/media/"
      - "./ms_registry:/app"
    # Use runserver for local development not uwsgi
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"

  postgres:
    image: postgres:14
    container_name: postgres-ms-registry
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ms_registry}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecret}
    volumes:
      - "ms_registry_dbdata:/var/lib/postgresql/data"
    # Expose port to localhost for debugging
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis:6.2
    container_name: redis-ms-registry

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-ms-registry
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=b0lag


volumes:
  ms_registry_dbdata:
  ms_registry_static_files:
  ms_registry_media_files:
