# Generated by Django 5.2.6 on 2026-03-19 14:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
        ("registry", "0002_alter_entityentitlement_entitlement_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusList",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("list_id", models.CharField(max_length=100, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("revocation", "Revocation"),
                            ("suspension", "Suspension"),
                        ],
                        default="revocation",
                        max_length=20,
                    ),
                ),
                (
                    "bits",
                    models.BinaryField(
                        default=b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                    ),
                ),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField(default=1024)),
            ],
            options={
                "verbose_name": "Status List",
                "verbose_name_plural": "Status Lists",
                "db_table": "wrprc_status_list",
            },
        ),
        migrations.CreateModel(
            name="SigningKey",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kid", models.CharField(max_length=100, unique=True)),
                ("algorithm", models.CharField(default="ES256", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rotated", "Rotated"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("public_key_jwk", models.JSONField()),
                (
                    "x5c",
                    models.JSONField(
                        default=list, help_text="Certificate chain for x5c header"
                    ),
                ),
                (
                    "external_key_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to key in HSM/KMS (e.g., AWS KMS key ARN)",
                        max_length=255,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="wrprc.signingkey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signing Key",
                "verbose_name_plural": "Signing Keys",
                "db_table": "wrprc_signing_key",
            },
        ),
        migrations.CreateModel(
            name="IssuedWRPRC",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_list_index", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
                ("jwt_hash", models.CharField(max_length=64)),
                ("jti", models.CharField(max_length=100, unique=True)),
                (
                    "intended_use",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wrprcs",
                        to="credentials.intendeduse",
                    ),
                ),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_wrprcs",
                        to="registry.registeredentity",
                    ),
                ),
                (
                    "status_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wrprcs",
                        to="wrprc.statuslist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issued WRPRC",
                "verbose_name_plural": "Issued WRPRCs",
                "db_table": "wrprc_issued",
                "indexes": [
                    models.Index(fields=["jti"], name="wrprc_issue_jti_5940cd_idx"),
                    models.Index(
                        fields=["registered_entity", "status"],
                        name="wrprc_issue_registe_787a1c_idx",
                    ),
                    models.Index(
                        fields=["status_list", "status_list_index"],
                        name="wrprc_issue_status__9fa1d3_idx",
                    ),
                ],
            },
        ),
    ]
