# Generated by Django 5.2.6 on 2026-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_identifier_value_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    (
                        "http://data.europa.eu/eudi/policy/privacy-policy",
                        "Privacy Policy",
                    )
                ],
                default="http://data.europa.eu/eudi/policy/privacy-policy",
                max_length=200,
            ),
        ),
    ]
