# Generated by Django 5.2.6 on 2026-05-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_policy_type_uri_data_migration"),
        ("credentials", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityprovidesattestation",
            name="registered_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_attestations",
                to="registry.registeredentity",
            ),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="registered_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intended_uses",
                to="registry.registeredentity",
            ),
        ),
        migrations.AddField(
            model_name="intendedusecredential",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intended_use_links",
                to="credentials.credential",
            ),
        ),
        migrations.AddField(
            model_name="intendedusecredential",
            name="intended_use",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_links",
                to="credentials.intendeduse",
            ),
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="credentials",
            field=models.ManyToManyField(
                related_name="intended_uses",
                through="credentials.IntendedUseCredential",
                to="credentials.credential",
            ),
        ),
        migrations.AddField(
            model_name="intendeduseprivacypolicy",
            name="intended_use",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privacy_policies",
                to="credentials.intendeduse",
            ),
        ),
        migrations.AddField(
            model_name="intendeduseprivacypolicy",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intended_use_links",
                to="core.policy",
            ),
        ),
        migrations.AddField(
            model_name="intendedusepurpose",
            name="intended_use",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purposes",
                to="credentials.intendeduse",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["credential"], name="credentials_credent_c8d778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityprovidesattestation",
            index=models.Index(
                fields=["registered_entity"], name="credentials_registe_0bfca5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityprovidesattestation",
            unique_together={("registered_entity", "credential")},
        ),
        migrations.AddIndex(
            model_name="intendedusecredential",
            index=models.Index(
                fields=["intended_use"], name="credentials_intende_f18700_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intendedusecredential",
            unique_together={("intended_use", "credential")},
        ),
        migrations.AddIndex(
            model_name="intendeduse",
            index=models.Index(
                fields=["registered_entity"], name="credentials_registe_adc046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intendeduse",
            index=models.Index(
                fields=["intended_use_identifier"],
                name="credentials_intende_5ae10f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intendeduseprivacypolicy",
            index=models.Index(
                fields=["intended_use"], name="credentials_intende_7898f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intendeduseprivacypolicy",
            unique_together={("intended_use", "policy")},
        ),
        migrations.AddIndex(
            model_name="intendedusepurpose",
            index=models.Index(
                fields=["intended_use"], name="credentials_intende_cda674_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intendedusepurpose",
            unique_together={("intended_use", "lang")},
        ),
    ]
