# Generated by Django 5.2.6 on 2026-02-03 12:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntendedUse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intended_use_identifier",
                    models.CharField(
                        help_text="Registrar-provided unique identifier, may match Registration Certificate ID",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("validity_start", models.DateField(help_text="Validity start date")),
                (
                    "validity_end",
                    models.DateField(
                        blank=True,
                        help_text="End date for validity (revoked or expired)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intended Use",
                "verbose_name_plural": "Intended Uses",
                "db_table": "rp_intended_use",
            },
        ),
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "law_uri",
                    models.URLField(
                        help_text="URI reference to the law", max_length=2048
                    ),
                ),
                (
                    "law_name",
                    models.CharField(help_text="Name of the law", max_length=500),
                ),
                (
                    "law_country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Law",
                "verbose_name_plural": "Laws",
                "db_table": "rp_law",
            },
        ),
        migrations.CreateModel(
            name="NaturalPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("given_name", models.CharField(max_length=200)),
                ("family_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2",
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Natural Person",
                "verbose_name_plural": "Natural Persons",
                "db_table": "rp_natural_person",
            },
        ),
        migrations.CreateModel(
            name="PhysicalAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True, help_text="City/Town", max_length=200, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="State/Province",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country_code",
                    models.CharField(help_text="ISO 3166-1 alpha-2", max_length=2),
                ),
                (
                    "address_type",
                    models.CharField(
                        default="registered",
                        help_text="registered, operational, etc.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical Address",
                "verbose_name_plural": "Physical Addresses",
                "db_table": "rp_physical_address",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("changed_by", models.CharField(blank=True, max_length=200, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "rp_audit_log",
                "indexes": [
                    models.Index(
                        fields=["table_name"], name="rp_audit_lo_table_n_d07242_idx"
                    ),
                    models.Index(
                        fields=["record_id"], name="rp_audit_lo_record__e2d1f9_idx"
                    ),
                    models.Index(
                        fields=["changed_at"], name="rp_audit_lo_changed_390378_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("sd-jwt-vc", "SD-JWT Verifiable Credential"),
                            ("dc+sd-jwt", "Digital Credential SD-JWT"),
                            ("mso_mdoc", "ISO mDL / mdoc Format"),
                            ("jwt_vc_json", "JWT VC JSON"),
                            ("ldp_vc", "JSON-LD VC with Data Integrity"),
                        ],
                        help_text="Attestation format",
                        max_length=50,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        help_text="Format-specific metadata per OpenID4VP Section 6.1"
                    ),
                ),
                (
                    "catalogue_schema_uri",
                    models.URLField(
                        blank=True,
                        help_text="Reference to attestation catalogue",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "attestation_rulebook_uri",
                    models.URLField(
                        blank=True,
                        help_text="URI to Attestation Rulebook",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "attestation_type",
                    models.CharField(
                        blank=True,
                        help_text="Self-declared attestation type (if not in catalogue)",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
                "db_table": "rp_credential",
                "indexes": [
                    models.Index(
                        fields=["format"], name="rp_credenti_format_b90e39_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("EUID", "European Unique Identifier"),
                            ("VAT_NUMBER", "VAT Registration Number"),
                            ("LEI", "Legal Entity Identifier"),
                            (
                                "EORI",
                                "Economic Operators Registration and Identification",
                            ),
                            (
                                "NATIONAL_BUSINESS_REG",
                                "National Business Register Number",
                            ),
                            ("NATIONAL_TAX_REG", "National Tax Registration Number"),
                            ("SERIAL_NUMBER", "Serial Number (Natural Person)"),
                            ("OTHER", "Other National Identifier"),
                        ],
                        default="EUID",
                        help_text="Type of identifier",
                        max_length=50,
                    ),
                ),
                (
                    "identifier_value",
                    models.CharField(
                        help_text="The identifier value", max_length=500, unique=True
                    ),
                ),
                (
                    "identifier_uri",
                    models.URLField(
                        blank=True,
                        help_text="Full URI (e.g., http://data.europa.eu/eudi/id/EUID)",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2",
                        max_length=2,
                        null=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Identifier",
                "verbose_name_plural": "Identifiers",
                "db_table": "rp_identifier",
                "indexes": [
                    models.Index(
                        fields=["identifier_type"],
                        name="rp_identifi_identif_c20b54_idx",
                    ),
                    models.Index(
                        fields=["identifier_value"],
                        name="rp_identifi_identif_c90ca4_idx",
                    ),
                ],
                "unique_together": {("identifier_type", "identifier_value")},
            },
        ),
        migrations.CreateModel(
            name="IntendedUseCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Whether this credential is required"
                    ),
                ),
                (
                    "request_order",
                    models.PositiveIntegerField(
                        blank=True, help_text="Order in presentation request", null=True
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intended_use_links",
                        to="rp_registration.credential",
                    ),
                ),
                (
                    "intended_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_links",
                        to="rp_registration.intendeduse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intended Use Credential",
                "verbose_name_plural": "Intended Use Credentials",
                "db_table": "rp_intended_use_credential",
            },
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="credentials",
            field=models.ManyToManyField(
                related_name="intended_uses",
                through="rp_registration.IntendedUseCredential",
                to="rp_registration.credential",
            ),
        ),
        migrations.CreateModel(
            name="IntendedUsePurpose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lang",
                    models.CharField(
                        help_text="Language code per ETSI TS 119 612 Annex E",
                        max_length=5,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Localized purpose description"),
                ),
                (
                    "intended_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purposes",
                        to="rp_registration.intendeduse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intended Use Purpose",
                "verbose_name_plural": "Intended Use Purposes",
                "db_table": "rp_intended_use_purpose",
            },
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("legal_person", "Legal Person"),
                            ("natural_person", "Natural Person"),
                        ],
                        help_text="Type of legal entity",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=320, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("info_uri", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "primary_identifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_entities",
                        to="rp_registration.identifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Entity",
                "verbose_name_plural": "Legal Entities",
                "db_table": "rp_legal_entity",
            },
        ),
        migrations.CreateModel(
            name="LegalEntityIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="rp_registration.identifier",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_identifiers",
                        to="rp_registration.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Entity Identifier",
                "verbose_name_plural": "Legal Entity Identifiers",
                "db_table": "rp_legal_entity_identifier",
            },
        ),
        migrations.AddField(
            model_name="legalentity",
            name="identifiers",
            field=models.ManyToManyField(
                related_name="legal_entities",
                through="rp_registration.LegalEntityIdentifier",
                to="rp_registration.identifier",
            ),
        ),
        migrations.CreateModel(
            name="LegalPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_name",
                    models.CharField(help_text="Official legal name", max_length=500),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        help_text="e.g., LLC, GmbH, AB, etc.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "legal_form_uri",
                    models.URLField(
                        blank=True,
                        help_text="URI to legal form definition",
                        max_length=2048,
                        null=True,
                    ),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "governing_law",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_persons",
                        to="rp_registration.law",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Person",
                "verbose_name_plural": "Legal Persons",
                "db_table": "rp_legal_person",
            },
        ),
        migrations.AddField(
            model_name="legalentity",
            name="legal_person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_entity",
                to="rp_registration.legalperson",
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="natural_person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_entity",
                to="rp_registration.naturalperson",
            ),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="physical_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_entities",
                to="rp_registration.physicaladdress",
            ),
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("Privacy_Statement", "Privacy Statement"),
                            ("Terms_of_Service", "Terms of Service"),
                            ("Data_Processing_Agreement", "Data Processing Agreement"),
                            ("Cookie_Policy", "Cookie Policy"),
                            ("Other", "Other"),
                        ],
                        default="Privacy_Statement",
                        max_length=50,
                    ),
                ),
                ("policy_uri", models.URLField(max_length=2048)),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        help_text="Language/locale code",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "db_table": "rp_policy",
                "indexes": [
                    models.Index(
                        fields=["policy_type"], name="rp_policy_policy__4d6893_idx"
                    ),
                    models.Index(
                        fields=["policy_uri"], name="rp_policy_policy__ecce37_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntendedUsePrivacyPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        help_text="Language/locale for this policy version",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "intended_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_policies",
                        to="rp_registration.intendeduse",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intended_use_links",
                        to="rp_registration.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intended Use Privacy Policy",
                "verbose_name_plural": "Intended Use Privacy Policies",
                "db_table": "rp_intended_use_privacy_policy",
            },
        ),
        migrations.CreateModel(
            name="RegisteredEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_role",
                    models.CharField(
                        choices=[
                            ("relying_party", "Relying Party (Verifier)"),
                            ("pid_provider", "PID Provider (Issuer)"),
                            ("attestation_provider", "Attestation Provider (Issuer)"),
                        ],
                        help_text="Primary role: RP (verifier), PID Provider, or Attestation Provider",
                        max_length=30,
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text="Common/service name [0..1]",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_psb",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the entity is a public sector body (relevant for PuB-EAA Providers)",
                        verbose_name="Is Public Sector Body",
                    ),
                ),
                (
                    "is_intermediary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the entity acts as an intermediary. Only applicable to Relying Parties.",
                    ),
                ),
                (
                    "registry_uri",
                    models.URLField(
                        help_text="National registry API URI, provided by Registrar (per Reg_03, Reg_04)",
                        max_length=2048,
                    ),
                ),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=200, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "legal_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_entity",
                        to="rp_registration.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registered Entity",
                "verbose_name_plural": "Registered Entities",
                "db_table": "rp_registered_entity",
            },
        ),
        migrations.AddField(
            model_name="intendeduse",
            name="registered_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intended_uses",
                to="rp_registration.registeredentity",
            ),
        ),
        migrations.CreateModel(
            name="EntityUsesIntermediary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("intermediary_identifier", models.CharField(max_length=500)),
                (
                    "intermediary_trade_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("intermediary_registry_uri", models.URLField(max_length=2048)),
                (
                    "relationship_start_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("relationship_end_date", models.DateField(blank=True, null=True)),
                (
                    "intermediary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients_using",
                        to="rp_registration.registeredentity",
                    ),
                ),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_intermediaries",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uses Intermediary",
                "verbose_name_plural": "Uses Intermediaries",
                "db_table": "rp_entity_uses_intermediary",
            },
        ),
        migrations.CreateModel(
            name="EntitySupportURI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("support_uri", models.URLField(max_length=2048)),
                (
                    "support_type",
                    models.CharField(
                        blank=True,
                        help_text="website, email, phone",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_uris",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support URI",
                "verbose_name_plural": "Support URIs",
                "db_table": "rp_entity_support_uri",
            },
        ),
        migrations.CreateModel(
            name="EntityServiceDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lang",
                    models.CharField(
                        help_text="Language code per ETSI TS 119 612 Annex E",
                        max_length=5,
                    ),
                ),
                ("content", models.TextField(help_text="Localized description")),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_descriptions",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Description",
                "verbose_name_plural": "Service Descriptions",
                "db_table": "rp_entity_service_description",
            },
        ),
        migrations.CreateModel(
            name="EntityProvidesAttestation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provided_by",
                        to="rp_registration.credential",
                    ),
                ),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provided_attestations",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provided Attestation",
                "verbose_name_plural": "Provided Attestations",
                "db_table": "rp_entity_provides_attestation",
            },
        ),
        migrations.CreateModel(
            name="EntityEntitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entitlement_uri",
                    models.URLField(
                        help_text="e.g., https://uri.etsi.org/19475/Entitlement/Service_Provider",
                        max_length=2048,
                    ),
                ),
                (
                    "entitlement_type",
                    models.CharField(
                        choices=[
                            ("Service_Provider", "Service Provider"),
                            ("QEAA_Provider", "Qualified EAA Provider"),
                            ("Non_Q_EAA_Provider", "Non-Qualified EAA Provider"),
                            ("PUB_EAA_Provider", "Public EAA Provider"),
                            ("PID_Provider", "PID Provider"),
                            ("Intermediary", "Intermediary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entitlement",
                "verbose_name_plural": "Entitlements",
                "db_table": "rp_entity_entitlement",
            },
        ),
        migrations.CreateModel(
            name="EntityAccessCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certificate_serial", models.CharField(max_length=100)),
                (
                    "certificate_fingerprint_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("issuer_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("ct_log_id", models.CharField(blank=True, max_length=200, null=True)),
                ("ct_log_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "ct_sct",
                    models.BinaryField(
                        blank=True, help_text="Signed Certificate Timestamp", null=True
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("certificate_pem", models.TextField(blank=True, null=True)),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_certificates",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Certificate",
                "verbose_name_plural": "Access Certificates",
                "db_table": "rp_entity_access_certificate",
            },
        ),
        migrations.CreateModel(
            name="RegisteredEntityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="rp_registration.policy",
                    ),
                ),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_links",
                        to="rp_registration.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Policy",
                "verbose_name_plural": "Entity Policies",
                "db_table": "rp_entity_policy",
            },
        ),
        migrations.AddField(
            model_name="registeredentity",
            name="policies",
            field=models.ManyToManyField(
                related_name="registered_entities",
                through="rp_registration.RegisteredEntityPolicy",
                to="rp_registration.policy",
            ),
        ),
        migrations.CreateModel(
            name="SupervisoryAuthority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("authority_name", models.CharField(max_length=500)),
                (
                    "country_code",
                    models.CharField(help_text="Member State", max_length=2),
                ),
                ("email", models.EmailField(blank=True, max_length=320, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("info_uri", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_authorities",
                        to="rp_registration.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisory Authority (DPA)",
                "verbose_name_plural": "Supervisory Authorities (DPAs)",
                "db_table": "rp_supervisory_authority",
            },
        ),
        migrations.AddField(
            model_name="registeredentity",
            name="supervisory_authority",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_entities",
                to="rp_registration.supervisoryauthority",
            ),
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.JSONField(
                        help_text="JSON path pointer to claim within credential per OpenID4VP Section 6.3"
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        help_text="Optional expected values for matching",
                        null=True,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="rp_registration.credential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "db_table": "rp_claim",
                "indexes": [
                    models.Index(
                        fields=["credential"], name="rp_claim_credent_1d087f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityRegistrationCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certificate_identifier", models.CharField(max_length=500)),
                (
                    "certificate_serial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issuer_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("certificate_pem", models.TextField(blank=True, null=True)),
                (
                    "intended_use",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_certificate",
                        to="rp_registration.intendeduse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Certificate",
                "verbose_name_plural": "Registration Certificates",
                "db_table": "rp_wrp_registration_certificate",
                "indexes": [
                    models.Index(
                        fields=["intended_use"], name="rp_wrp_regi_intende_4379a4_idx"
                    ),
                    models.Index(
                        fields=["certificate_identifier"],
                        name="rp_wrp_regi_certifi_c9e164_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="intendedusecredential",
            index=models.Index(
                fields=["intended_use"], name="rp_intended_intende_7bd476_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intendedusecredential",
            unique_together={("intended_use", "credential")},
        ),
        migrations.AddIndex(
            model_name="intendedusepurpose",
            index=models.Index(
                fields=["intended_use"], name="rp_intended_intende_f05ee4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intendedusepurpose",
            unique_together={("intended_use", "lang")},
        ),
        migrations.AlterUniqueTogether(
            name="legalentityidentifier",
            unique_together={("legal_entity", "identifier")},
        ),
        migrations.AddIndex(
            model_name="legalperson",
            index=models.Index(
                fields=["legal_name"], name="rp_legal_pe_legal_n_413961_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalentity",
            index=models.Index(
                fields=["entity_type"], name="rp_legal_en_entity__13f155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intendeduseprivacypolicy",
            index=models.Index(
                fields=["intended_use"], name="rp_intended_intende_c12dcc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intendeduseprivacypolicy",
            unique_together={("intended_use", "policy")},
        ),
        migrations.AddIndex(
            model_name="intendeduse",
            index=models.Index(
                fields=["registered_entity"], name="rp_intended_registe_c2f3ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intendeduse",
            index=models.Index(
                fields=["intended_use_identifier"],
                name="rp_intended_intende_48d05d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entityusesintermediary",
            index=models.Index(
                fields=["registered_entity"], name="rp_entity_u_registe_d32f7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityusesintermediary",
            index=models.Index(
                fields=["intermediary"], name="rp_entity_u_interme_1deefe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityusesintermediary",
            unique_together={("registered_entity", "intermediary")},
        ),
        migrations.AddIndex(
            model_name="entitysupporturi",
            index=models.Index(
                fields=["registered_entity"], name="rp_entity_s_registe_be3d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityservicedescription",
            index=models.Index(
                fields=["registered_entity"], name="rp_entity_s_registe_18c874_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityservicedescription",
            unique_together={("registered_entity", "lang")},
        ),
        migrations.AddIndex(
            model_name="entityprovidesattestation",
            index=models.Index(
                fields=["registered_entity"], name="rp_entity_p_registe_08a787_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityprovidesattestation",
            unique_together={("registered_entity", "credential")},
        ),
        migrations.AddIndex(
            model_name="entityentitlement",
            index=models.Index(
                fields=["registered_entity"], name="rp_entity_e_registe_2c2476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityentitlement",
            index=models.Index(
                fields=["entitlement_type"], name="rp_entity_e_entitle_5bbe4d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityentitlement",
            unique_together={("registered_entity", "entitlement_uri")},
        ),
        migrations.AddIndex(
            model_name="entityaccesscertificate",
            index=models.Index(
                fields=["registered_entity"], name="rp_entity_a_registe_d90841_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityaccesscertificate",
            index=models.Index(
                fields=["is_current"], name="rp_entity_a_is_curr_2f7f4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityaccesscertificate",
            index=models.Index(
                fields=["not_before", "not_after"],
                name="rp_entity_a_not_bef_c0119d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registeredentitypolicy",
            unique_together={("registered_entity", "policy")},
        ),
        migrations.AddIndex(
            model_name="supervisoryauthority",
            index=models.Index(
                fields=["country_code"], name="rp_supervis_country_d9a5f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registeredentity",
            index=models.Index(
                fields=["entity_role"], name="rp_register_entity__4a296a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registeredentity",
            index=models.Index(
                fields=["trade_name"], name="rp_register_trade_n_815705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registeredentity",
            index=models.Index(
                fields=["registry_uri"], name="rp_register_registr_3b6b9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registeredentity",
            index=models.Index(fields=["is_psb"], name="rp_register_is_psb_44c97a_idx"),
        ),
        migrations.AddIndex(
            model_name="registeredentity",
            index=models.Index(
                fields=["is_intermediary"], name="rp_register_is_inte_7cb3ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registeredentity",
            index=models.Index(
                fields=["registration_status"], name="rp_register_registr_bb376b_idx"
            ),
        ),
    ]
