# Generated by Django 5.2.6 on 2026-02-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rp_registration", "0001_initial"),
        ("tsl_generator", "0006_alter_servicehistoryinstance_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredentity",
            name="trust_service_provider",
            field=models.OneToOneField(
                blank=True,
                help_text="Corresponding TSP entry in the Trusted List (eIDAS 2.0 integration)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_entity",
                to="tsl_generator.trustserviceprovider",
            ),
        ),
    ]
