# Generated by Django 5.2.6 on 2026-02-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rp_registration", "0002_registeredentity_trust_service_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredentity",
            name="trust_service_provider",
        ),
    ]
