"""
Input serializers for IntendedUse submitted during WRP onboarding.

These are write-only; the read representation is produced by
WalletRelyingPartySerializer.to_representation() in registry/serializers.py.
"""

import uuid
from datetime import date

from core.models import CredentialFormat, Policy, PolicyType
from rest_framework import serializers

from .models import (
    Claim,
    Credential,
    IntendedUse,
    IntendedUseCredential,
    IntendedUsePrivacyPolicy,
    IntendedUsePurpose,
)


class ClaimInputSerializer(serializers.Serializer):
    path = serializers.ListField(
        child=serializers.CharField(),
        min_length=1,
        help_text=(
            "JSON path array per OpenID4VP §6.3, e.g. ['given_name'] or"
            " ['address', 'street_address']"
        ),
    )
    values = serializers.JSONField(
        required=False,
        allow_null=True,
        help_text="Optional expected values for claim matching",
    )


class CredentialInputSerializer(serializers.Serializer):
    format = serializers.ChoiceField(
        choices=CredentialFormat.choices,
        help_text="Credential format (dc+sd-jwt, mso_mdoc, …)",
    )
    meta = serializers.JSONField(
        help_text="Format-specific metadata, e.g. {vct_values: [...]} for dc+sd-jwt",
    )
    claims = ClaimInputSerializer(
        many=True,
        required=False,
        help_text=(
            "Attributes to request; omit to allow any attribute in this credential"
        ),
    )


class IntendedUsePurposeInputSerializer(serializers.Serializer):
    lang = serializers.CharField(
        max_length=5,
        help_text="BCP 47 language tag, e.g. 'en-US', 'de-DE'",
    )
    content = serializers.CharField(
        help_text="Purpose description in the specified language",
    )


class IntendedUsePrivacyPolicyInputSerializer(serializers.Serializer):
    policy_uri = serializers.URLField(
        help_text="URL of the privacy policy document",
    )
    locale = serializers.CharField(
        max_length=5,
        required=False,
        allow_null=True,
        help_text="Language/locale for this policy version",
    )
    is_primary = serializers.BooleanField(
        default=False,
        help_text="Mark as primary privacy policy for this intended use",
    )


class IntendedUseInputSerializer(serializers.Serializer):
    """
    Single intended use declaration submitted during WRP onboarding.

    intendedUseIdentifier is registrar-assigned — it is generated automatically
    on creation and must not be supplied by the entity.

    Per B.2.7 Class IntendedUse:
      - purposes      [1..*]
      - privacy_policy [1..*]
      - credentials   [1..*]
    """

    purposes = IntendedUsePurposeInputSerializer(
        many=True,
        help_text="Multilingual purpose descriptions [1..*] per B.2.7",
    )
    privacy_policy = IntendedUsePrivacyPolicyInputSerializer(
        many=True,
        help_text="Privacy policy links [1..*] per B.2.7",
    )
    credentials = CredentialInputSerializer(
        many=True,
        help_text="Credential types to request [1..*] per B.2.7",
    )

    def validate_purposes(self, value):
        if not value:
            raise serializers.ValidationError(
                "At least one purpose is required per B.2.7."
            )
        return value

    def validate_privacy_policy(self, value):
        if not value:
            raise serializers.ValidationError(
                "At least one privacy policy is required per B.2.7."
            )
        return value

    def validate_credentials(self, value):
        if not value:
            raise serializers.ValidationError(
                "At least one credential is required per B.2.7."
            )
        return value


def create_intended_use(registered_entity, validated_data: dict) -> IntendedUse:
    """
    Create an IntendedUse and all nested records from already-validated data.

    Called from WalletRelyingPartySerializer.create() after the entity exists.
    The intendedUseIdentifier is auto-generated by the registrar.
    """
    identifier = f"IU-{uuid.uuid4().hex[:12].upper()}"

    intended_use = IntendedUse.objects.create(
        registered_entity=registered_entity,
        intended_use_identifier=identifier,
        validity_start=date.today(),
    )

    # Purposes [1..*]
    for p in validated_data["purposes"]:
        IntendedUsePurpose.objects.create(
            intended_use=intended_use,
            lang=p["lang"],
            content=p["content"],
        )

    # Privacy policies [1..*] — make first entry primary if none explicitly marked
    pp_list = validated_data["privacy_policy"]
    has_explicit_primary = any(pp.get("is_primary") for pp in pp_list)
    for idx, pp_data in enumerate(pp_list):
        policy, _ = Policy.objects.get_or_create(
            policy_uri=pp_data["policy_uri"],
            defaults={"policy_type": PolicyType.PRIVACY_STATEMENT},
        )
        is_primary = pp_data.get("is_primary", False)
        if not has_explicit_primary and idx == 0:
            is_primary = True
        IntendedUsePrivacyPolicy.objects.create(
            intended_use=intended_use,
            policy=policy,
            locale=pp_data.get("locale"),
            is_primary=is_primary,
        )

    # Credentials [1..*] with optional claims
    for cred_data in validated_data["credentials"]:
        credential = Credential.objects.create(
            format=cred_data["format"],
            meta=cred_data["meta"],
        )
        for claim_data in cred_data.get("claims", []):
            Claim.objects.create(
                credential=credential,
                path=claim_data["path"],
                values=claim_data.get("values"),
            )
        IntendedUseCredential.objects.create(
            intended_use=intended_use,
            credential=credential,
        )

    return intended_use
