# Generated by Django 5.2.6 on 2026-04-09 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("legal_entities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceHistoryInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                                "Qualified Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                                "Public Key Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                                "Qualified Time Stamping Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA",
                                "Time Stamping Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                                "Qualified OCSP Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                                "CRL Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                                "Qualified Electronic Delivery Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                                "Qualified Registered Electronic Mail",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                                "Qualified Preservation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                                "Qualified Validation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                                "Identity Verification Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                                "Identity Verification (non-PKI)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/WalletProvider",
                                "EUDI Wallet Provider",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IndividualWalletProvider",
                                "Individual Wallet Provider (Natural Person)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/LegalPersonWalletProvider",
                                "Legal Person Wallet Provider",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PID_Issuer",
                                "PID Issuer - Person Identification Data Issuer",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/QEAA_Provider",
                                "QEAA Provider - Qualified Electronic Attestation of Attributes",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PUB_EAA_Provider",
                                "PuB-EAA Provider - Public Body Attestation Provider",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/Non_Q_EAA_Provider",
                                "Non-Qualified EAA Provider",
                            ),
                        ],
                        help_text="Service type at this point in history",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                                "Granted",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn",
                                "Withdrawn",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/suspended",
                                "Suspended",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/recognisedatnationallevel",
                                "Recognised at National Level",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/deprecatedatnationallevel",
                                "Deprecated at National Level",
                            ),
                        ],
                        help_text="Status at this point in history",
                        max_length=200,
                    ),
                ),
                (
                    "status_starting_time",
                    models.DateTimeField(
                        help_text="When this historical status became effective"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service History Instance",
                "verbose_name_plural": "Service History Instances",
                "ordering": ["-status_starting_time"],
            },
        ),
        migrations.CreateModel(
            name="TrustService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                                "Qualified Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                                "Public Key Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                                "Qualified Time Stamping Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA",
                                "Time Stamping Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                                "Qualified OCSP Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                                "CRL Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                                "Qualified Electronic Delivery Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                                "Qualified Registered Electronic Mail",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                                "Qualified Preservation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                                "Qualified Validation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                                "Identity Verification Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                                "Identity Verification (non-PKI)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/WalletProvider",
                                "EUDI Wallet Provider",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IndividualWalletProvider",
                                "Individual Wallet Provider (Natural Person)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/LegalPersonWalletProvider",
                                "Legal Person Wallet Provider",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PID_Issuer",
                                "PID Issuer - Person Identification Data Issuer",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/QEAA_Provider",
                                "QEAA Provider - Qualified Electronic Attestation of Attributes",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PUB_EAA_Provider",
                                "PuB-EAA Provider - Public Body Attestation Provider",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/Non_Q_EAA_Provider",
                                "Non-Qualified EAA Provider",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        help_text="Service type identifier URI",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                                "Granted",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn",
                                "Withdrawn",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/suspended",
                                "Suspended",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/recognisedatnationallevel",
                                "Recognised at National Level",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/deprecatedatnationallevel",
                                "Deprecated at National Level",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                        help_text="Current service status",
                        max_length=200,
                    ),
                ),
                (
                    "status_starting_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this status became effective",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Trust Service",
                "verbose_name_plural": "Trust Services",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="TSLPointer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tsl_location",
                    models.URLField(
                        help_text="URL of the referenced TSL", max_length=500
                    ),
                ),
                (
                    "tsl_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUlistofthelists",
                                "EU List of Trusted Lists (LOTL)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                                "EU Generic Trusted List",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/CClist",
                                "Country Code Trusted List",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                        help_text="Type of the referenced TSL",
                        max_length=200,
                    ),
                ),
                (
                    "scheme_territory",
                    models.CharField(
                        help_text="Territory of the referenced TSL", max_length=2
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/vnd.etsi.tsl+xml",
                        help_text="MIME type of the TSL",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "TSL Pointer",
                "verbose_name_plural": "TSL Pointers",
                "ordering": ["scheme_territory"],
            },
        ),
        migrations.CreateModel(
            name="TSLScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this scheme", max_length=200
                    ),
                ),
                (
                    "tsl_id",
                    models.CharField(
                        default="id_for_enveloped_signing_of_the_entire_list",
                        help_text="TSL identifier used as the Id attribute in the root XML element (e.g. BE-TL-071)",
                        max_length=200,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="TSL version identifier (TSLVersionIdentifier)",
                    ),
                ),
                (
                    "tsl_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUlistofthelists",
                                "EU List of Trusted Lists (LOTL)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                                "EU Generic Trusted List",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/CClist",
                                "Country Code Trusted List",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                        help_text="TSL Type URI",
                        max_length=200,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="TSL sequence number (increments with each update)",
                    ),
                ),
                (
                    "territory",
                    models.CharField(
                        default="SE",
                        help_text="Two-letter country code (ISO 3166-1 alpha-2)",
                        max_length=2,
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="TSL issue date/time",
                    ),
                ),
                (
                    "next_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expected next update date/time",
                        null=True,
                    ),
                ),
                (
                    "distribution_points",
                    models.TextField(
                        blank=True, help_text="Distribution point URIs (one per line)"
                    ),
                ),
                (
                    "historical_information_period",
                    models.PositiveIntegerField(
                        default=65535, help_text="Historical information period in days"
                    ),
                ),
                (
                    "status_determination_approach",
                    models.URLField(
                        default="http://uri.etsi.org/TrstSvc/TrustedList/StatusDetn/EUappropriate",
                        help_text="Status determination approach URI (TS 119 612 clause 5.3.17)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TSL Scheme",
                "verbose_name_plural": "TSL Schemes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryDigitalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x509_subject_name",
                    models.CharField(
                        blank=True,
                        help_text="X.509 Subject Distinguished Name (e.g., CN=..., O=..., C=...)",
                        max_length=1000,
                    ),
                ),
                (
                    "x509_ski",
                    models.CharField(
                        blank=True,
                        help_text="X.509 Subject Key Identifier (Base64 encoded)",
                        max_length=200,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_ids",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Digital ID",
                "verbose_name_plural": "History Digital IDs",
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryAdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        help_text="Additional service information URI", max_length=200
                    ),
                ),
                ("language", models.CharField(default="en", max_length=5)),
                (
                    "critical",
                    models.BooleanField(
                        default=True, help_text="Whether this extension is critical"
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Additional Info",
                "verbose_name_plural": "History Additional Info",
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Service Name",
                "verbose_name_plural": "History Service Names",
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualifier_uri",
                    models.CharField(
                        help_text="Qualifier URI (e.g., QCNoQSCD)", max_length=200
                    ),
                ),
                (
                    "criteria_assert",
                    models.CharField(
                        default="none",
                        help_text="Criteria list assertion type",
                        max_length=20,
                    ),
                ),
                ("key_usage", models.BooleanField(default=False)),
                ("key_usage_digital_signature", models.BooleanField(default=False)),
                ("key_usage_non_repudiation", models.BooleanField(default=True)),
                ("key_usage_key_encipherment", models.BooleanField(default=False)),
                ("key_usage_data_encipherment", models.BooleanField(default=False)),
                ("key_usage_key_agreement", models.BooleanField(default=False)),
                ("key_usage_key_cert_sign", models.BooleanField(default=False)),
                ("key_usage_crl_sign", models.BooleanField(default=False)),
                ("key_usage_encipher_only", models.BooleanField(default=False)),
                ("key_usage_decipher_only", models.BooleanField(default=False)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Qualification",
                "verbose_name_plural": "History Qualifications",
            },
        ),
        migrations.CreateModel(
            name="ServiceSupplyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.URLField(
                        help_text="Service supply point URI", max_length=500
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_points",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Supply Point",
                "verbose_name_plural": "Service Supply Points",
            },
        ),
        migrations.CreateModel(
            name="ServiceQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualifier_uri",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCNoSSCD",
                                "QC No SSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCNoQSCD",
                                "QC No QSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCWithSSCD",
                                "QC With SSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCWithQSCD",
                                "QC With QSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCQSCDManagedOnBehalf",
                                "QC QSCD Managed On Behalf",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCQSCDStatusAsInCert",
                                "QC QSCD Status As In Cert",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForESig",
                                "QC For ESig",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForESeal",
                                "QC For ESeal",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForWSA",
                                "QC For Web Site Authentication",
                            ),
                        ],
                        help_text="Qualifier URI (e.g., QCNoQSCD)",
                        max_length=200,
                    ),
                ),
                (
                    "criteria_assert",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("atLeastOne", "At Least One"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="Criteria list assertion type",
                        max_length=20,
                    ),
                ),
                (
                    "key_usage",
                    models.BooleanField(
                        default=False, help_text="Include key usage criteria"
                    ),
                ),
                ("key_usage_digital_signature", models.BooleanField(default=False)),
                ("key_usage_non_repudiation", models.BooleanField(default=True)),
                ("key_usage_key_encipherment", models.BooleanField(default=False)),
                ("key_usage_data_encipherment", models.BooleanField(default=False)),
                ("key_usage_key_agreement", models.BooleanField(default=False)),
                ("key_usage_key_cert_sign", models.BooleanField(default=False)),
                ("key_usage_crl_sign", models.BooleanField(default=False)),
                ("key_usage_encipher_only", models.BooleanField(default=False)),
                ("key_usage_decipher_only", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Qualification",
                "verbose_name_plural": "Service Qualifications",
            },
        ),
        migrations.CreateModel(
            name="ServiceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Name",
                "verbose_name_plural": "Service Names",
            },
        ),
        migrations.AddField(
            model_name="servicehistoryinstance",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="tsl_generator.trustservice",
            ),
        ),
        migrations.CreateModel(
            name="ServiceDefinitionURI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definition_uris",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Definition URI",
                "verbose_name_plural": "Service Definition URIs",
            },
        ),
        migrations.CreateModel(
            name="ServiceCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        help_text="PEM-encoded X.509 certificate (including BEGIN/END markers)"
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True, help_text="Subject Common Name", max_length=500
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True, help_text="Issuer Common Name", max_length=500
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                (
                    "x509_subject_name",
                    models.CharField(
                        blank=True,
                        help_text="X.509 Subject Distinguished Name (e.g., CN=..., O=..., C=...)",
                        max_length=1000,
                    ),
                ),
                (
                    "x509_ski",
                    models.CharField(
                        blank=True,
                        help_text="X.509 Subject Key Identifier (Base64 encoded)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Certificate",
                "verbose_name_plural": "Service Certificates",
            },
        ),
        migrations.CreateModel(
            name="AdditionalServiceInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForeSignatures",
                                "For e-Signatures",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForeSeals",
                                "For e-Seals",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForWebSiteAuthentication",
                                "For Web Site Authentication",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/RootCA-QC",
                                "Root CA QC",
                            ),
                        ],
                        help_text="Additional service information URI",
                        max_length=200,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "critical",
                    models.BooleanField(
                        default=True, help_text="Whether this extension is critical"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_service_info",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Service Information",
                "verbose_name_plural": "Additional Service Information",
            },
        ),
        migrations.CreateModel(
            name="TrustServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        help_text="Organization providing the trust services",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_service_providers",
                        to="legal_entities.legalentity",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Service Provider",
                "verbose_name_plural": "Trust Service Providers",
                "ordering": ["pk"],
                "unique_together": {("scheme", "legal_entity")},
            },
        ),
        migrations.AddField(
            model_name="trustservice",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="tsl_generator.trustserviceprovider",
            ),
        ),
        migrations.CreateModel(
            name="TSLPointerCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_data",
                    models.TextField(
                        help_text="Base64-encoded X.509 certificate (PEM content without headers)"
                    ),
                ),
                (
                    "pointer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tsl_generator.tslpointer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointer Certificate",
                "verbose_name_plural": "Pointer Certificates",
            },
        ),
        migrations.CreateModel(
            name="TSLPointerOperatorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "pointer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_names",
                        to="tsl_generator.tslpointer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointer Operator Name",
                "verbose_name_plural": "Pointer Operator Names",
            },
        ),
        migrations.CreateModel(
            name="TSLPolicyOrLegalNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("notice", models.TextField(help_text="Legal notice or policy text")),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_notices",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Notice",
                "verbose_name_plural": "Legal Notices",
            },
        ),
        migrations.AddField(
            model_name="tslpointer",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pointers",
                to="tsl_generator.tslscheme",
            ),
        ),
        migrations.CreateModel(
            name="TSLSchemeCommunityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_rules",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Rule",
                "verbose_name_plural": "Community Rules",
            },
        ),
        migrations.CreateModel(
            name="TSLSchemeInformationURI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_uris",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Information URI",
                "verbose_name_plural": "Scheme Information URIs",
            },
        ),
        migrations.CreateModel(
            name="TSLSchemeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_names",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Name",
                "verbose_name_plural": "Scheme Names",
            },
        ),
        migrations.CreateModel(
            name="TSLSchemeOperatorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_names",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator Name",
                "verbose_name_plural": "Operator Names",
            },
        ),
        migrations.CreateModel(
            name="TSPCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        help_text="PEM-encoded X.509 certificate (including BEGIN/END markers)"
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("signing", "Signing Certificate"),
                            ("identity", "Identity Certificate"),
                            ("tls", "TLS Certificate"),
                            ("other", "Other"),
                        ],
                        default="identity",
                        help_text="Type/purpose of this certificate",
                        max_length=50,
                    ),
                ),
                (
                    "subject_dn",
                    models.CharField(
                        blank=True,
                        help_text="Subject Distinguished Name",
                        max_length=1000,
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True, help_text="Subject Common Name", max_length=500
                    ),
                ),
                (
                    "issuer_dn",
                    models.CharField(
                        blank=True,
                        help_text="Issuer Distinguished Name",
                        max_length=1000,
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True, help_text="Issuer Common Name", max_length=500
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Certificate serial number (hex)",
                        max_length=100,
                    ),
                ),
                (
                    "fingerprint_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 fingerprint (hex, no colons)",
                        max_length=64,
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True, help_text="Certificate validity start", null=True
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True, help_text="Certificate validity end", null=True
                    ),
                ),
                (
                    "key_usage",
                    models.CharField(
                        blank=True,
                        help_text="Key usage extensions (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "extended_key_usage",
                    models.CharField(
                        blank=True,
                        help_text="Extended key usage OIDs (comma-separated)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Certificate",
                "verbose_name_plural": "TSP Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TSPElectronicAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        help_text="Electronic address URI (https://, mailto:, tel:)",
                        max_length=500,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electronic_addresses",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electronic Address",
                "verbose_name_plural": "Electronic Addresses",
            },
        ),
        migrations.CreateModel(
            name="TSPInformationURI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_uris",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Information URI",
                "verbose_name_plural": "TSP Information URIs",
            },
        ),
        migrations.CreateModel(
            name="TSPName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Name",
                "verbose_name_plural": "TSP Names",
            },
        ),
        migrations.CreateModel(
            name="TSPTradeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_names",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Trade Name",
                "verbose_name_plural": "TSP Trade Names",
            },
        ),
    ]
