# Generated by Django 5.2.6 on 2026-01-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0003_additionalserviceinformation_servicequalification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceHistoryAdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        help_text="Additional service information URI", max_length=200
                    ),
                ),
                ("language", models.CharField(default="en", max_length=5)),
                (
                    "critical",
                    models.BooleanField(
                        default=True, help_text="Whether this extension is critical"
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Additional Info",
                "verbose_name_plural": "History Additional Info",
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryDigitalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x509_subject_name",
                    models.CharField(
                        blank=True,
                        help_text="X.509 Subject Distinguished Name (e.g., CN=..., O=..., C=...)",
                        max_length=1000,
                    ),
                ),
                (
                    "x509_ski",
                    models.CharField(
                        blank=True,
                        help_text="X.509 Subject Key Identifier (Base64 encoded)",
                        max_length=200,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_ids",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Digital ID",
                "verbose_name_plural": "History Digital IDs",
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualifier_uri",
                    models.CharField(
                        help_text="Qualifier URI (e.g., QCNoQSCD)", max_length=200
                    ),
                ),
                (
                    "criteria_assert",
                    models.CharField(
                        default="none",
                        help_text="Criteria list assertion type",
                        max_length=20,
                    ),
                ),
                ("key_usage", models.BooleanField(default=False)),
                ("key_usage_digital_signature", models.BooleanField(default=False)),
                ("key_usage_non_repudiation", models.BooleanField(default=True)),
                ("key_usage_key_encipherment", models.BooleanField(default=False)),
                ("key_usage_data_encipherment", models.BooleanField(default=False)),
                ("key_usage_key_agreement", models.BooleanField(default=False)),
                ("key_usage_key_cert_sign", models.BooleanField(default=False)),
                ("key_usage_crl_sign", models.BooleanField(default=False)),
                ("key_usage_encipher_only", models.BooleanField(default=False)),
                ("key_usage_decipher_only", models.BooleanField(default=False)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Qualification",
                "verbose_name_plural": "History Qualifications",
            },
        ),
    ]
