# Generated by Django 5.2.6 on 2026-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0005_add_x509_fields_to_service_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicehistoryinstance",
            name="service_type",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        "Qualified Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                        "Public Key Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                        "Qualified Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/TSS-QC",
                        "Time Stamping Service - Qualified",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                        "Qualified OCSP Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                        "CRL Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                        "Qualified Electronic Delivery Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                        "Qualified Registered Electronic Mail",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                        "Qualified Preservation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                        "Qualified Validation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                        "Identity Verification Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                        "Identity Verification (non-PKI)",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/PIDProvider",
                        "PID Provider - Person Identification Data Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/QEAAProvider",
                        "QEAA Provider - Qualified Electronic Attestation of Attributes Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/EAAProvider",
                        "EAA Provider - Electronic Attestation of Attributes Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/WalletProvider",
                        "EUDI Wallet Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/RelyingParty",
                        "EUDI Wallet Relying Party",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/PuB-EAAProvider",
                        "PuB-EAA Provider - Public Body Attestation Issuer",
                    ),
                ],
                help_text="Service type at this point in history",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="trustservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        "Qualified Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                        "Public Key Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                        "Qualified Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/TSS-QC",
                        "Time Stamping Service - Qualified",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                        "Qualified OCSP Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                        "CRL Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                        "Qualified Electronic Delivery Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                        "Qualified Registered Electronic Mail",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                        "Qualified Preservation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                        "Qualified Validation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                        "Identity Verification Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                        "Identity Verification (non-PKI)",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/PIDProvider",
                        "PID Provider - Person Identification Data Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/QEAAProvider",
                        "QEAA Provider - Qualified Electronic Attestation of Attributes Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/EAAProvider",
                        "EAA Provider - Electronic Attestation of Attributes Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/WalletProvider",
                        "EUDI Wallet Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/RelyingParty",
                        "EUDI Wallet Relying Party",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EudiWallet/PuB-EAAProvider",
                        "PuB-EAA Provider - Public Body Attestation Issuer",
                    ),
                ],
                default="http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                help_text="Service type identifier URI",
                max_length=200,
            ),
        ),
    ]
