# Generated by Django 5.2.6 on 2026-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0008_alter_servicehistoryinstance_service_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tslscheme",
            name="status_determination_approach",
            field=models.URLField(
                default="http://uri.etsi.org/TrstSvc/TrustedList/StatusDetn/EUappropriate",
                help_text="Status determination approach URI (TS 119 612 clause 5.3.17)",
                max_length=500,
            ),
        ),
    ]
