# Generated by Django 5.2.6 on 2026-02-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_entities", "0001_initial"),
        ("tsl_generator", "0009_alter_tslscheme_status_determination_approach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trustserviceprovider",
            name="legal_entity",
            field=models.ForeignKey(
                help_text="Organization providing the trust services",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_service_providers",
                to="legal_entities.legalentity",
            ),
        ),
    ]
