# Generated by Django 5.2.6 on 2026-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0010_alter_trustserviceprovider_legal_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="tslscheme",
            name="tsl_id",
            field=models.CharField(
                default="id_for_enveloped_signing_of_the_entire_list",
                help_text="TSL identifier used as the Id attribute in the root XML element (e.g. BE-TL-071)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tslscheme",
            name="version",
            field=models.PositiveIntegerField(
                default=5, help_text="TSL version identifier (TSLVersionIdentifier)"
            ),
        ),
    ]
