# Generated by Django 5.2.6 on 2026-02-12 13:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("changed_by", models.CharField(blank=True, max_length=200, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "certificates_audit_log",
                "indexes": [
                    models.Index(
                        fields=["table_name"], name="certificate_table_n_dba420_idx"
                    ),
                    models.Index(
                        fields=["record_id"], name="certificate_record__02466b_idx"
                    ),
                    models.Index(
                        fields=["changed_at"], name="certificate_changed_a84df9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityAccessCertificate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_serial", models.CharField(max_length=100)),
                (
                    "certificate_fingerprint_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("issuer_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("ct_log_id", models.CharField(blank=True, max_length=200, null=True)),
                ("ct_log_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "ct_sct",
                    models.BinaryField(
                        blank=True, help_text="Signed Certificate Timestamp", null=True
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("certificate_pem", models.TextField(blank=True, null=True)),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_certificates",
                        to="registry.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Certificate",
                "verbose_name_plural": "Access Certificates",
                "db_table": "certificates_entity_access_certificate",
                "indexes": [
                    models.Index(
                        fields=["registered_entity"],
                        name="certificate_registe_58eb4e_idx",
                    ),
                    models.Index(
                        fields=["is_current"], name="certificate_is_curr_4a488d_idx"
                    ),
                    models.Index(
                        fields=["not_before", "not_after"],
                        name="certificate_not_bef_84ed62_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityRegistrationCertificate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_identifier", models.CharField(max_length=500)),
                (
                    "certificate_serial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issuer_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("certificate_pem", models.TextField(blank=True, null=True)),
                (
                    "intended_use",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_certificate",
                        to="credentials.intendeduse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Certificate",
                "verbose_name_plural": "Registration Certificates",
                "db_table": "certificates_entity_registration_certificate",
                "indexes": [
                    models.Index(
                        fields=["intended_use"], name="certificate_intende_dd9e30_idx"
                    ),
                    models.Index(
                        fields=["certificate_identifier"],
                        name="certificate_certifi_1a0918_idx",
                    ),
                ],
            },
        ),
    ]
