# Generated by Django 5.2.6 on 2026-05-28 13:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_ca", "0054_alter_certificate_serial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityRegistrationCertificate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_identifier", models.CharField(max_length=500)),
                (
                    "certificate_serial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issuer_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("certificate_pem", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Registration Certificate",
                "verbose_name_plural": "Registration Certificates",
                "db_table": "certificates_entity_registration_certificate",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("changed_by", models.CharField(blank=True, max_length=200, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "certificates_audit_log",
                "indexes": [
                    models.Index(
                        fields=["table_name"], name="certificate_table_n_dba420_idx"
                    ),
                    models.Index(
                        fields=["record_id"], name="certificate_record__02466b_idx"
                    ),
                    models.Index(
                        fields=["changed_at"], name="certificate_changed_a84df9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityAccessCertificate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_serial", models.CharField(max_length=100)),
                (
                    "certificate_fingerprint_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("issuer_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("not_before", models.DateTimeField()),
                ("not_after", models.DateTimeField()),
                ("is_current", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("certificate_pem", models.TextField(blank=True, null=True)),
                (
                    "django_ca_certificate",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to django-ca Certificate for lifecycle management",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registry_access_certificate",
                        to="django_ca.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Certificate",
                "verbose_name_plural": "Access Certificates",
                "db_table": "certificates_entity_access_certificate",
            },
        ),
    ]
