# Generated by Django 5.2.6 on 2026-05-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("credentials", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityaccesscertificate",
            name="registered_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_certificates",
                to="registry.registeredentity",
            ),
        ),
        migrations.AddField(
            model_name="entityregistrationcertificate",
            name="intended_use",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_certificate",
                to="credentials.intendeduse",
            ),
        ),
        migrations.AddIndex(
            model_name="entityaccesscertificate",
            index=models.Index(
                fields=["registered_entity"], name="certificate_registe_58eb4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityaccesscertificate",
            index=models.Index(
                fields=["is_current"], name="certificate_is_curr_4a488d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityaccesscertificate",
            index=models.Index(
                fields=["not_before", "not_after"],
                name="certificate_not_bef_84ed62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entityregistrationcertificate",
            index=models.Index(
                fields=["intended_use"], name="certificate_intende_dd9e30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entityregistrationcertificate",
            index=models.Index(
                fields=["certificate_identifier"], name="certificate_certifi_1a0918_idx"
            ),
        ),
    ]
