# Generated by Django 5.2.6 on 2026-06-04 10:15

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_initial"),
        ("registry", "0003_add_domain_uri_to_registered_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntitySigningCertificate",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entitlement_type",
                    models.CharField(
                        choices=[
                            ("PID_Provider", "PID Provider"),
                            ("QEAA_Provider", "Qualified EAA Provider"),
                            ("PUB_EAA_Provider", "Public EAA Provider"),
                            ("Non_Q_EAA_Provider", "Non-Qualified EAA Provider"),
                        ],
                        help_text="Issuer entitlement this signing cert covers",
                        max_length=50,
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        help_text="PEM-encoded self-signed X.509 certificate provided by the entity"
                    ),
                ),
                (
                    "certificate_serial",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "certificate_fingerprint_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("subject_dn", models.CharField(blank=True, max_length=500, null=True)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registered_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing_certificates",
                        to="registry.registeredentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signing Certificate",
                "verbose_name_plural": "Signing Certificates",
                "db_table": "certificates_entity_signing_certificate",
                "indexes": [
                    models.Index(
                        fields=["registered_entity", "entitlement_type"],
                        name="certificate_registe_0993ac_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("registered_entity", "entitlement_type"),
                        name="unique_current_signing_cert_per_entitlement",
                    )
                ],
            },
        ),
    ]
