# Generated by Django 5.2.6 on 2026-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="identifier_value",
            field=models.CharField(help_text="The identifier value", max_length=500),
        ),
    ]
