"""
Tests for IntendedUse:
  - created during WRP onboarding  (POST /registry/wrp/)
  - managed post-registration       (GET/POST /registry/wrp/{pk}/intended-use/)
  - detail / revoke           (GET/DELETE /registry/wrp/{pk}/intended-use/{iu_id}/)
"""

import uuid

import pytest
from credentials.models import IntendedUse
from django.urls import reverse
from registry.tests.factories import RegisteredEntityFactory
from rest_framework import status

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

_IU_PAYLOAD = {
    "purposes": [
        {"lang": "en-US", "content": "Required for checking minimum age"},
        {"lang": "de-DE", "content": "Benötigt für die Überprüfung des Mindestalters"},
    ],
    "privacy_policy": [{"policy_uri": "https://example.com/privacy"}],
    "credentials": [
        {
            "format": "dc+sd-jwt",
            "meta": {
                "vct_values": ["https://credentials.example.com/identity_credential"]
            },
            "claims": [
                {"path": ["given_name"]},
                {"path": ["family_name"]},
                {"path": ["address", "street_address"]},
            ],
        }
    ],
}


def _wrp_payload(**overrides):
    payload = {
        "legal_entity_identifier": "5493001KSF2Z4PTCYX31",
        "legal_entity_identifier_type": "LEI",
        "legal_name": "Example GmbH",
        "country_code": "DE",
        "entitlements": ["https://uri.etsi.org/19475/Entitlement/Service_Provider"],
        "support_uris": ["https://example.com/support"],
        "supervisory_authority_name": "BfDI",
        "supervisory_authority_country": "DE",
    }
    payload.update(overrides)
    return payload


def _list_url(entity_pk):
    return reverse("registry:intended-use-list-create", args=[entity_pk])


def _detail_url(entity_pk, iu_id):
    return reverse("registry:intended-use-detail", args=[entity_pk, iu_id])


# ---------------------------------------------------------------------------
# Onboarding: POST /registry/wrp/ with intended_use
# ---------------------------------------------------------------------------


@pytest.mark.django_db
def test_wrp_create_without_intended_use_returns_201(authenticated_api_client):
    """Backward compat — intended_use is optional."""
    response = authenticated_api_client.post(
        reverse("registry:wrp"), _wrp_payload(), format="json"
    )
    assert response.status_code == status.HTTP_201_CREATED
    assert IntendedUse.objects.count() == 0


@pytest.mark.django_db
def test_wrp_create_with_intended_use_returns_201(authenticated_api_client):
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD])
    response = authenticated_api_client.post(
        reverse("registry:wrp"), payload, format="json"
    )
    assert response.status_code == status.HTTP_201_CREATED


@pytest.mark.django_db
def test_wrp_create_with_intended_use_stores_in_db(authenticated_api_client):
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD])
    authenticated_api_client.post(reverse("registry:wrp"), payload, format="json")
    assert IntendedUse.objects.count() == 1


@pytest.mark.django_db
def test_wrp_create_intended_use_identifier_is_registrar_assigned(
    authenticated_api_client,
):
    """intendedUseIdentifier must be generated by the registrar, not supplied."""
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD])
    authenticated_api_client.post(reverse("registry:wrp"), payload, format="json")
    iu = IntendedUse.objects.get()
    assert iu.intended_use_identifier.startswith("IU-")


@pytest.mark.django_db
def test_wrp_create_intended_use_purposes_stored(authenticated_api_client):
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD])
    authenticated_api_client.post(reverse("registry:wrp"), payload, format="json")
    iu = IntendedUse.objects.get()
    langs = set(iu.purposes.values_list("lang", flat=True))
    assert langs == {"en-US", "de-DE"}


@pytest.mark.django_db
def test_wrp_create_intended_use_credentials_stored(authenticated_api_client):
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD])
    authenticated_api_client.post(reverse("registry:wrp"), payload, format="json")
    iu = IntendedUse.objects.get()
    assert iu.credential_links.count() == 1
    cred = iu.credential_links.first().credential
    assert cred.format == "dc+sd-jwt"
    assert cred.claims.count() == 3


@pytest.mark.django_db
def test_wrp_create_multiple_intended_uses(authenticated_api_client):
    second_iu = {
        **_IU_PAYLOAD,
        "purposes": [{"lang": "en", "content": "Identity verification"}],
        "privacy_policy": [{"policy_uri": "https://example.com/privacy2"}],
    }
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD, second_iu])
    authenticated_api_client.post(reverse("registry:wrp"), payload, format="json")
    assert IntendedUse.objects.count() == 2


@pytest.mark.django_db
def test_wrp_create_with_invalid_intended_use_returns_400(authenticated_api_client):
    """Missing required purposes → 400."""
    bad_iu = {**_IU_PAYLOAD, "purposes": []}
    payload = _wrp_payload(intended_use=[bad_iu])
    response = authenticated_api_client.post(
        reverse("registry:wrp"), payload, format="json"
    )
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_wrp_create_intended_use_in_response(authenticated_api_client):
    """The created intendedUse is visible in the response."""
    payload = _wrp_payload(intended_use=[_IU_PAYLOAD])
    response = authenticated_api_client.post(
        reverse("registry:wrp"), payload, format="json"
    )
    assert response.status_code == status.HTTP_201_CREATED
    intended_use = response.data.get("intendedUse")
    assert intended_use is not None
    assert len(intended_use) == 1
    assert intended_use[0]["intendedUseIdentifier"].startswith("IU-")


# ---------------------------------------------------------------------------
# List / Create  GET|POST /registry/wrp/{pk}/intended-use/
# ---------------------------------------------------------------------------


@pytest.mark.django_db
def test_list_intended_uses_empty(authenticated_api_client):
    entity = RegisteredEntityFactory()
    response = authenticated_api_client.get(_list_url(entity.pk))
    assert response.status_code == status.HTTP_200_OK
    assert response.data == []


@pytest.mark.django_db
def test_list_intended_uses_returns_existing(authenticated_api_client):
    from credentials.serializers import create_intended_use

    entity = RegisteredEntityFactory()
    create_intended_use(entity, _IU_PAYLOAD)
    response = authenticated_api_client.get(_list_url(entity.pk))
    assert response.status_code == status.HTTP_200_OK
    assert len(response.data) == 1


@pytest.mark.django_db
def test_list_intended_uses_unknown_entity_returns_404(authenticated_api_client):
    response = authenticated_api_client.get(_list_url(uuid.uuid4()))
    assert response.status_code == status.HTTP_404_NOT_FOUND


@pytest.mark.django_db
def test_create_intended_use_post_returns_201(authenticated_api_client):
    entity = RegisteredEntityFactory()
    response = authenticated_api_client.post(
        _list_url(entity.pk), _IU_PAYLOAD, format="json"
    )
    assert response.status_code == status.HTTP_201_CREATED


@pytest.mark.django_db
def test_create_intended_use_post_stores_in_db(authenticated_api_client):
    entity = RegisteredEntityFactory()
    authenticated_api_client.post(_list_url(entity.pk), _IU_PAYLOAD, format="json")
    assert IntendedUse.objects.filter(registered_entity=entity).count() == 1


@pytest.mark.django_db
def test_create_intended_use_response_contains_identifier(authenticated_api_client):
    entity = RegisteredEntityFactory()
    response = authenticated_api_client.post(
        _list_url(entity.pk), _IU_PAYLOAD, format="json"
    )
    assert response.data["intendedUseIdentifier"].startswith("IU-")


@pytest.mark.django_db
def test_create_intended_use_missing_credentials_returns_400(authenticated_api_client):
    entity = RegisteredEntityFactory()
    bad_payload = {**_IU_PAYLOAD, "credentials": []}
    response = authenticated_api_client.post(
        _list_url(entity.pk), bad_payload, format="json"
    )
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_create_intended_use_missing_privacy_policy_returns_400(
    authenticated_api_client,
):
    entity = RegisteredEntityFactory()
    bad_payload = {**_IU_PAYLOAD, "privacy_policy": []}
    response = authenticated_api_client.post(
        _list_url(entity.pk), bad_payload, format="json"
    )
    assert response.status_code == status.HTTP_400_BAD_REQUEST


@pytest.mark.django_db
def test_create_intended_use_unknown_entity_returns_404(authenticated_api_client):
    response = authenticated_api_client.post(
        _list_url(uuid.uuid4()), _IU_PAYLOAD, format="json"
    )
    assert response.status_code == status.HTTP_404_NOT_FOUND


# ---------------------------------------------------------------------------
# Detail / Revoke  GET|DELETE /registry/wrp/{pk}/intended-use/{iu_id}/
# ---------------------------------------------------------------------------


@pytest.mark.django_db
def test_get_intended_use_returns_200(authenticated_api_client):
    from credentials.serializers import create_intended_use

    entity = RegisteredEntityFactory()
    iu = create_intended_use(entity, _IU_PAYLOAD)
    response = authenticated_api_client.get(_detail_url(entity.pk, iu.pk))
    assert response.status_code == status.HTTP_200_OK
    assert response.data["intendedUseIdentifier"] == iu.intended_use_identifier


@pytest.mark.django_db
def test_get_intended_use_wrong_entity_returns_404(authenticated_api_client):
    """Cannot access an intended use via a different entity's URL."""
    from credentials.serializers import create_intended_use

    entity = RegisteredEntityFactory()
    other_entity = RegisteredEntityFactory()
    iu = create_intended_use(entity, _IU_PAYLOAD)
    response = authenticated_api_client.get(_detail_url(other_entity.pk, iu.pk))
    assert response.status_code == status.HTTP_404_NOT_FOUND


@pytest.mark.django_db
def test_get_intended_use_unknown_id_returns_404(authenticated_api_client):
    entity = RegisteredEntityFactory()
    response = authenticated_api_client.get(_detail_url(entity.pk, uuid.uuid4()))
    assert response.status_code == status.HTTP_404_NOT_FOUND


@pytest.mark.django_db
def test_revoke_intended_use_returns_204(authenticated_api_client):
    from credentials.serializers import create_intended_use

    entity = RegisteredEntityFactory()
    iu = create_intended_use(entity, _IU_PAYLOAD)
    response = authenticated_api_client.delete(_detail_url(entity.pk, iu.pk))
    assert response.status_code == status.HTTP_204_NO_CONTENT


@pytest.mark.django_db
def test_revoke_sets_validity_end(authenticated_api_client):
    from datetime import date

    from credentials.serializers import create_intended_use

    entity = RegisteredEntityFactory()
    iu = create_intended_use(entity, _IU_PAYLOAD)
    authenticated_api_client.delete(_detail_url(entity.pk, iu.pk))
    iu.refresh_from_db()
    assert iu.validity_end == date.today()


@pytest.mark.django_db
def test_revoke_is_idempotent(authenticated_api_client):
    from credentials.serializers import create_intended_use

    entity = RegisteredEntityFactory()
    iu = create_intended_use(entity, _IU_PAYLOAD)
    authenticated_api_client.delete(_detail_url(entity.pk, iu.pk))
    response = authenticated_api_client.delete(_detail_url(entity.pk, iu.pk))
    assert response.status_code == status.HTTP_204_NO_CONTENT
