# Generated by Django 5.2.6 on 2026-01-13 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceHistoryInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                                "Qualified Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                                "Public Key Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                                "Qualified Time Stamping Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA/TSS-QC",
                                "Time Stamping Service - Qualified",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                                "Qualified Electronic Delivery Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                                "Qualified Registered Electronic Mail",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                                "Qualified Preservation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                                "Qualified Validation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                                "Identity Verification Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                                "Identity Verification (non-PKI)",
                            ),
                        ],
                        help_text="Service type at this point in history",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                                "Granted",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn",
                                "Withdrawn",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/recognisedatnationallevel",
                                "Recognised at National Level",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/deprecatedatnationallevel",
                                "Deprecated at National Level",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/undersupervision",
                                "Under Supervision",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionincessation",
                                "Supervision in Cessation",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionceased",
                                "Supervision Ceased",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionrevoked",
                                "Supervision Revoked",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accredited",
                                "Accredited",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accreditationceased",
                                "Accreditation Ceased",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accreditationrevoked",
                                "Accreditation Revoked",
                            ),
                        ],
                        help_text="Status at this point in history",
                        max_length=200,
                    ),
                ),
                (
                    "status_starting_time",
                    models.DateTimeField(
                        help_text="When this historical status became effective"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service History Instance",
                "verbose_name_plural": "Service History Instances",
                "ordering": ["-status_starting_time"],
            },
        ),
        migrations.CreateModel(
            name="TrustService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                                "Qualified Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                                "Public Key Certificate Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                                "Qualified Time Stamping Authority",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/TSA/TSS-QC",
                                "Time Stamping Service - Qualified",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                                "Qualified Electronic Delivery Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                                "Qualified Registered Electronic Mail",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                                "Qualified Preservation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                                "Qualified Validation Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                                "Identity Verification Service",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                                "Identity Verification (non-PKI)",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        help_text="Service type identifier URI",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                                "Granted",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn",
                                "Withdrawn",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/recognisedatnationallevel",
                                "Recognised at National Level",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/deprecatedatnationallevel",
                                "Deprecated at National Level",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/undersupervision",
                                "Under Supervision",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionincessation",
                                "Supervision in Cessation",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionceased",
                                "Supervision Ceased",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionrevoked",
                                "Supervision Revoked",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accredited",
                                "Accredited",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accreditationceased",
                                "Accreditation Ceased",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accreditationrevoked",
                                "Accreditation Revoked",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                        help_text="Current service status",
                        max_length=200,
                    ),
                ),
                (
                    "status_starting_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this status became effective",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Trust Service",
                "verbose_name_plural": "Trust Services",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="TrustServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(blank=True, max_length=500)),
                ("locality", models.CharField(blank=True, max_length=200)),
                ("state_or_province", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=50)),
                (
                    "country_name",
                    models.CharField(
                        default="SE", help_text="ISO 3166-1 alpha-2", max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Trust Service Provider",
                "verbose_name_plural": "Trust Service Providers",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="TSLPointer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tsl_location",
                    models.URLField(
                        help_text="URL of the referenced TSL", max_length=500
                    ),
                ),
                (
                    "tsl_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUlistofthelists",
                                "EU List of Trusted Lists (LOTL)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                                "EU Generic Trusted List",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/CClist",
                                "Country Code Trusted List",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                        help_text="Type of the referenced TSL",
                        max_length=200,
                    ),
                ),
                (
                    "scheme_territory",
                    models.CharField(
                        help_text="Territory of the referenced TSL", max_length=2
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/vnd.etsi.tsl+xml",
                        help_text="MIME type of the TSL",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "TSL Pointer",
                "verbose_name_plural": "TSL Pointers",
                "ordering": ["scheme_territory"],
            },
        ),
        migrations.CreateModel(
            name="TSLScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this scheme", max_length=200
                    ),
                ),
                (
                    "tsl_type",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUlistofthelists",
                                "EU List of Trusted Lists (LOTL)",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                                "EU Generic Trusted List",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/TSLType/CClist",
                                "Country Code Trusted List",
                            ),
                        ],
                        default="http://uri.etsi.org/TrstSvc/TrustedList/TSLType/EUgeneric",
                        help_text="TSL Type URI",
                        max_length=200,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="TSL sequence number (increments with each update)",
                    ),
                ),
                (
                    "territory",
                    models.CharField(
                        default="SE",
                        help_text="Two-letter country code (ISO 3166-1 alpha-2)",
                        max_length=2,
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="TSL issue date/time",
                    ),
                ),
                (
                    "next_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expected next update date/time",
                        null=True,
                    ),
                ),
                (
                    "distribution_points",
                    models.TextField(
                        blank=True, help_text="Distribution point URIs (one per line)"
                    ),
                ),
                (
                    "historical_information_period",
                    models.PositiveIntegerField(
                        default=65535, help_text="Historical information period in days"
                    ),
                ),
                (
                    "status_determination_approach",
                    models.URLField(
                        default="http://uri.etsi.org/TrstSvc/TrustedList/TSLType/StatusDetn/EUappropriate",
                        help_text="Status determination approach URI",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "TSL Scheme",
                "verbose_name_plural": "TSL Schemes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceHistoryName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsl_generator.servicehistoryinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "History Service Name",
                "verbose_name_plural": "History Service Names",
            },
        ),
        migrations.CreateModel(
            name="ServiceSupplyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.URLField(
                        help_text="Service supply point URI", max_length=500
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_points",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Supply Point",
                "verbose_name_plural": "Service Supply Points",
            },
        ),
        migrations.CreateModel(
            name="ServiceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Name",
                "verbose_name_plural": "Service Names",
            },
        ),
        migrations.AddField(
            model_name="servicehistoryinstance",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="tsl_generator.trustservice",
            ),
        ),
        migrations.CreateModel(
            name="ServiceDefinitionURI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definition_uris",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Definition URI",
                "verbose_name_plural": "Service Definition URIs",
            },
        ),
        migrations.CreateModel(
            name="ServiceCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        help_text="PEM-encoded X.509 certificate (including BEGIN/END markers)"
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True, help_text="Subject Common Name", max_length=500
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True, help_text="Issuer Common Name", max_length=500
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Certificate",
                "verbose_name_plural": "Service Certificates",
            },
        ),
        migrations.AddField(
            model_name="trustservice",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="tsl_generator.trustserviceprovider",
            ),
        ),
        migrations.CreateModel(
            name="TSLPointerCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_data",
                    models.TextField(
                        help_text="Base64-encoded X.509 certificate (PEM content without headers)"
                    ),
                ),
                (
                    "pointer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tsl_generator.tslpointer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointer Certificate",
                "verbose_name_plural": "Pointer Certificates",
            },
        ),
        migrations.CreateModel(
            name="TSLPointerOperatorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "pointer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_names",
                        to="tsl_generator.tslpointer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointer Operator Name",
                "verbose_name_plural": "Pointer Operator Names",
            },
        ),
        migrations.CreateModel(
            name="TSLPolicyOrLegalNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("notice", models.TextField(help_text="Legal notice or policy text")),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_notices",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Notice",
                "verbose_name_plural": "Legal Notices",
            },
        ),
        migrations.AddField(
            model_name="tslpointer",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pointers",
                to="tsl_generator.tslscheme",
            ),
        ),
        migrations.AddField(
            model_name="trustserviceprovider",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="providers",
                to="tsl_generator.tslscheme",
            ),
        ),
        migrations.CreateModel(
            name="TSLSchemeCommunityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_rules",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Rule",
                "verbose_name_plural": "Community Rules",
            },
        ),
        migrations.CreateModel(
            name="TSLSchemeInformationURI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_uris",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Information URI",
                "verbose_name_plural": "Scheme Information URIs",
            },
        ),
        migrations.CreateModel(
            name="TSLSchemeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_names",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Name",
                "verbose_name_plural": "Scheme Names",
            },
        ),
        migrations.CreateModel(
            name="TSLSchemeOperatorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_names",
                        to="tsl_generator.tslscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator Name",
                "verbose_name_plural": "Operator Names",
            },
        ),
        migrations.CreateModel(
            name="TSPElectronicAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        help_text="Electronic address URI (https://, mailto:, tel:)",
                        max_length=500,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electronic_addresses",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electronic Address",
                "verbose_name_plural": "Electronic Addresses",
            },
        ),
        migrations.CreateModel(
            name="TSPInformationURI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("uri", models.URLField(max_length=500)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_uris",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Information URI",
                "verbose_name_plural": "TSP Information URIs",
            },
        ),
        migrations.CreateModel(
            name="TSPName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Name",
                "verbose_name_plural": "TSP Names",
            },
        ),
        migrations.CreateModel(
            name="TSPTradeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_names",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Trade Name",
                "verbose_name_plural": "TSP Trade Names",
            },
        ),
    ]
