# Generated by Django 5.2.6 on 2026-01-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TSPCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        help_text="PEM-encoded X.509 certificate (including BEGIN/END markers)"
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("signing", "Signing Certificate"),
                            ("identity", "Identity Certificate"),
                            ("tls", "TLS Certificate"),
                            ("other", "Other"),
                        ],
                        default="identity",
                        help_text="Type/purpose of this certificate",
                        max_length=50,
                    ),
                ),
                (
                    "subject_dn",
                    models.CharField(
                        blank=True,
                        help_text="Subject Distinguished Name",
                        max_length=1000,
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True, help_text="Subject Common Name", max_length=500
                    ),
                ),
                (
                    "issuer_dn",
                    models.CharField(
                        blank=True,
                        help_text="Issuer Distinguished Name",
                        max_length=1000,
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True, help_text="Issuer Common Name", max_length=500
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Certificate serial number (hex)",
                        max_length=100,
                    ),
                ),
                (
                    "fingerprint_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 fingerprint (hex, no colons)",
                        max_length=64,
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True, help_text="Certificate validity start", null=True
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True, help_text="Certificate validity end", null=True
                    ),
                ),
                (
                    "key_usage",
                    models.CharField(
                        blank=True,
                        help_text="Key usage extensions (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "extended_key_usage",
                    models.CharField(
                        blank=True,
                        help_text="Extended key usage OIDs (comma-separated)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tsl_generator.trustserviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "TSP Certificate",
                "verbose_name_plural": "TSP Certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
