# Generated by Django 5.2.6 on 2026-01-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0002_tspcertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalServiceInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForeSignatures",
                                "For e-Signatures",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForeSeals",
                                "For e-Seals",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/ForWebSiteAuthentication",
                                "For Web Site Authentication",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/RootCA-QC",
                                "Root CA QC",
                            ),
                        ],
                        help_text="Additional service information URI",
                        max_length=200,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sv", "Swedish"),
                            ("de", "German"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("nl", "Dutch"),
                            ("da", "Danish"),
                            ("fi", "Finnish"),
                            ("no", "Norwegian"),
                            ("pl", "Polish"),
                            ("pt", "Portuguese"),
                            ("cs", "Czech"),
                            ("el", "Greek"),
                            ("hu", "Hungarian"),
                            ("ro", "Romanian"),
                            ("sk", "Slovak"),
                            ("sl", "Slovenian"),
                            ("bg", "Bulgarian"),
                            ("et", "Estonian"),
                            ("lv", "Latvian"),
                            ("lt", "Lithuanian"),
                            ("mt", "Maltese"),
                            ("hr", "Croatian"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "critical",
                    models.BooleanField(
                        default=True, help_text="Whether this extension is critical"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_service_info",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Service Information",
                "verbose_name_plural": "Additional Service Information",
            },
        ),
        migrations.CreateModel(
            name="ServiceQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualifier_uri",
                    models.CharField(
                        choices=[
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCNoSSCD",
                                "QC No SSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCNoQSCD",
                                "QC No QSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCWithSSCD",
                                "QC With SSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCWithQSCD",
                                "QC With QSCD",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCQSCDManagedOnBehalf",
                                "QC QSCD Managed On Behalf",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCQSCDStatusAsInCert",
                                "QC QSCD Status As In Cert",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForESig",
                                "QC For ESig",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForESeal",
                                "QC For ESeal",
                            ),
                            (
                                "http://uri.etsi.org/TrstSvc/TrustedList/SvcInfoExt/QCForWSA",
                                "QC For Web Site Authentication",
                            ),
                        ],
                        help_text="Qualifier URI (e.g., QCNoQSCD)",
                        max_length=200,
                    ),
                ),
                (
                    "criteria_assert",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("atLeastOne", "At Least One"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="Criteria list assertion type",
                        max_length=20,
                    ),
                ),
                (
                    "key_usage",
                    models.BooleanField(
                        default=False, help_text="Include key usage criteria"
                    ),
                ),
                ("key_usage_digital_signature", models.BooleanField(default=False)),
                ("key_usage_non_repudiation", models.BooleanField(default=True)),
                ("key_usage_key_encipherment", models.BooleanField(default=False)),
                ("key_usage_data_encipherment", models.BooleanField(default=False)),
                ("key_usage_key_agreement", models.BooleanField(default=False)),
                ("key_usage_key_cert_sign", models.BooleanField(default=False)),
                ("key_usage_crl_sign", models.BooleanField(default=False)),
                ("key_usage_encipher_only", models.BooleanField(default=False)),
                ("key_usage_decipher_only", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="tsl_generator.trustservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Qualification",
                "verbose_name_plural": "Service Qualifications",
            },
        ),
    ]
