# Generated by Django 5.2.6 on 2026-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tsl_generator",
            "0004_servicehistoryadditionalinfo_servicehistorydigitalid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecertificate",
            name="x509_ski",
            field=models.CharField(
                blank=True,
                help_text="X.509 Subject Key Identifier (Base64 encoded)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="servicecertificate",
            name="x509_subject_name",
            field=models.CharField(
                blank=True,
                help_text="X.509 Subject Distinguished Name (e.g., CN=..., O=..., C=...)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="servicehistoryinstance",
            name="service_type",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        "Qualified Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                        "Public Key Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                        "Qualified Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/TSS-QC",
                        "Time Stamping Service - Qualified",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                        "Qualified OCSP Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                        "CRL Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                        "Qualified Electronic Delivery Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                        "Qualified Registered Electronic Mail",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                        "Qualified Preservation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                        "Qualified Validation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                        "Identity Verification Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                        "Identity Verification (non-PKI)",
                    ),
                ],
                help_text="Service type at this point in history",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="trustservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        "Qualified Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                        "Public Key Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                        "Qualified Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/TSS-QC",
                        "Time Stamping Service - Qualified",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                        "Qualified OCSP Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                        "CRL Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                        "Qualified Electronic Delivery Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                        "Qualified Registered Electronic Mail",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                        "Qualified Preservation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                        "Qualified Validation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                        "Identity Verification Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                        "Identity Verification (non-PKI)",
                    ),
                ],
                default="http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                help_text="Service type identifier URI",
                max_length=200,
            ),
        ),
    ]
