# Generated by Django 5.2.6 on 2026-02-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rp_registration", "0003_remove_registeredentity_trust_service_provider"),
        ("tsl_generator", "0006_alter_servicehistoryinstance_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustserviceprovider",
            name="legal_entity",
            field=models.ForeignKey(
                default=1,
                help_text="Organization providing the trust services",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_service_providers",
                to="rp_registration.legalentity",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="trustserviceprovider",
            unique_together={("scheme", "legal_entity")},
        ),
        migrations.RemoveField(
            model_name="trustserviceprovider",
            name="country_name",
        ),
        migrations.RemoveField(
            model_name="trustserviceprovider",
            name="locality",
        ),
        migrations.RemoveField(
            model_name="trustserviceprovider",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="trustserviceprovider",
            name="state_or_province",
        ),
        migrations.RemoveField(
            model_name="trustserviceprovider",
            name="street_address",
        ),
    ]
