# Generated by Django 5.2.6 on 2026-02-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tsl_generator", "0007_alter_trustserviceprovider_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicehistoryinstance",
            name="service_type",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        "Qualified Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                        "Public Key Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                        "Qualified Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA",
                        "Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                        "Qualified OCSP Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                        "CRL Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                        "Qualified Electronic Delivery Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                        "Qualified Registered Electronic Mail",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                        "Qualified Preservation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                        "Qualified Validation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                        "Identity Verification Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                        "Identity Verification (non-PKI)",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/WalletProvider",
                        "EUDI Wallet Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IndividualWalletProvider",
                        "Individual Wallet Provider (Natural Person)",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/LegalPersonWalletProvider",
                        "Legal Person Wallet Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PID_Issuer",
                        "PID Issuer - Person Identification Data Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QEAA_Provider",
                        "QEAA Provider - Qualified Electronic Attestation of Attributes",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PUB_EAA_Provider",
                        "PuB-EAA Provider - Public Body Attestation Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Non_Q_EAA_Provider",
                        "Non-Qualified EAA Provider",
                    ),
                ],
                help_text="Service type at this point in history",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="servicehistoryinstance",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                        "Granted",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn",
                        "Withdrawn",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/suspended",
                        "Suspended",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/recognisedatnationallevel",
                        "Recognised at National Level",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/deprecatedatnationallevel",
                        "Deprecated at National Level",
                    ),
                ],
                help_text="Status at this point in history",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="trustservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                        "Qualified Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/CA/PKC",
                        "Public Key Certificate Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA/QTST",
                        "Qualified Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/TSA",
                        "Time Stamping Authority",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/OCSP/QC",
                        "Qualified OCSP Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Certstatus/CRL",
                        "CRL Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/Q",
                        "Qualified Electronic Delivery Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/EDS/REM/Q",
                        "Qualified Registered Electronic Mail",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PSES/Q",
                        "Qualified Preservation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QESValidation/Q",
                        "Qualified Validation Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV",
                        "Identity Verification Service",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IdV/nothavingPKIid",
                        "Identity Verification (non-PKI)",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/WalletProvider",
                        "EUDI Wallet Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/IndividualWalletProvider",
                        "Individual Wallet Provider (Natural Person)",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/LegalPersonWalletProvider",
                        "Legal Person Wallet Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PID_Issuer",
                        "PID Issuer - Person Identification Data Issuer",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/QEAA_Provider",
                        "QEAA Provider - Qualified Electronic Attestation of Attributes",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/PUB_EAA_Provider",
                        "PuB-EAA Provider - Public Body Attestation Provider",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/Svctype/Non_Q_EAA_Provider",
                        "Non-Qualified EAA Provider",
                    ),
                ],
                default="http://uri.etsi.org/TrstSvc/Svctype/CA/QC",
                help_text="Service type identifier URI",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="trustservice",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                        "Granted",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn",
                        "Withdrawn",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/suspended",
                        "Suspended",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/recognisedatnationallevel",
                        "Recognised at National Level",
                    ),
                    (
                        "http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/deprecatedatnationallevel",
                        "Deprecated at National Level",
                    ),
                ],
                default="http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted",
                help_text="Current service status",
                max_length=200,
            ),
        ),
    ]
